### ISSUE TITLE
By injecting got fsdevCommitDevice() failed using v0.1.1 also v0.1.0

### ISSUE THREAD

**Issue by vansoest** [3096/nut#1]
firmware: 4.0.1 used hekate-ipl-4x and started it with the hbc.
using nut version 0.1.1
by injecting I've got fsdevCommitDevice() failed by injecting my zelda botw saves.

with version 0.1.0 injecting the savestates is also not correctly working.
the inject directory goes empty or it copies some files and then crashed with the same error fsdevCommitDevice()

**Comment by 3096** [comment]
fsdevCommitDevice() fails when injecting too many files. I'm not exactly sure why yet. When editing botw I recommend only putting the one folder of the save state that you're editing inside `inject`. You can identify the correct save state that you want for editing by looking at the thumbnail inside its folder.

**Comment by vansoest** [comment]
Compiled and tested another tool https://github.com/BernardoGiordano/Checkpoint
works without problems restored my complete zelda botw savestates included thumbnails, camera etc. in one action!

**Comment by 3096** [comment]
Yay, Bernardo fixed checkpoint ^_^
Well like my description in the repo, checkpoint should always be preferred when it works. I wrote this to use only when Checkpoint doesn't work.

**Comment by 3096** [comment]
This should be fixed now.
