### ISSUE TITLE
D Pad selection not working?

### ISSUE THREAD

**Issue by meisaboo** [3096/nut#7]
I opened the program up from homebrew and whenever I try using up/down on the dpad there's no response. I tried pressing every button and nothing seems to happen.

**Comment by 3096** [comment]
Could be caused by the recent HID change. Are you on 9.0.0 by any chance?
I'll probably make a new working build tomorrow then.

**Comment by meisaboo** [comment]
Yeah I believe I'm on 9.0.0 right now. That's probably the problem, but
anyways thanks for the quick response! L

**Comment by 3096** [comment]
Fixed! https://github.com/3096/nut/releases

**Comment by meisaboo** [comment]
Thank you so much! I really appreciate it
